//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Car_warkshop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admins
    {
        public int Id_admin { get; set; }
        public string Login_admin { get; set; }
        public string Password_admin { get; set; }
    }
}
