//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Car_warkshop
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Car_warkshopEntities : DbContext
    {
        public Car_warkshopEntities()
            : base("name=Car_warkshopEntities")
        {
        }
        private static Car_warkshopEntities _context;


        public static Car_warkshopEntities GetContext()
        {
            if (_context == null)
                _context = new Car_warkshopEntities();

            return _context;
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admins> Admins { get; set; }
        public virtual DbSet<Car_mechanic> Car_mechanic { get; set; }
        public virtual DbSet<Choice_services> Choice_services { get; set; }
        public virtual DbSet<Customer_data> Customer_data { get; set; }
        public virtual DbSet<Servis> Servis { get; set; }
    }
}
