//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Car_warkshop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Choice_services
    {
        public int Id_release { get; set; }
        public int Id_client { get; set; }
        public int Id_servis { get; set; }
        public System.DateTime Date_order { get; set; }
    
        public virtual Customer_data Customer_data { get; set; }
        public virtual Servis Servis { get; set; }
    }
}
